package com.bluezhang.supperapp.fragments;


import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Intent;
import android.database.Cursor;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.CursorLoader;
import android.support.v4.content.Loader;
import android.support.v4.widget.CursorAdapter;
import android.support.v4.widget.SimpleCursorAdapter;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;
import com.bluezhang.supperapp.R;
import com.bluezhang.supperapp.ResetActivity;
import com.bluezhang.supperapp.providers.DataContract;

/**
 * A simple {@link Fragment} subclass.
 */
public class HistoryListFragment extends Fragment implements LoaderManager.LoaderCallbacks<Cursor>, AdapterView.OnItemClickListener {

    private ListView listView;

    private SimpleCursorAdapter adapter;


    public HistoryListFragment() {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View ret = inflater.inflate(R.layout.fragment_history_list, container, false);
        listView = (ListView) ret.findViewById(R.id.history_list_view);
        if (listView != null) {
                adapter = new SimpleCursorAdapter(
                        getContext(),
                        android.R.layout.simple_list_item_1,
                        null,//Cursor
                        new String[]{DataContract.History.URL},
                        new int[]{android.R.id.text1},
                        CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER
                );
                listView.setAdapter(adapter);
                 listView.setOnItemClickListener(this);
                //Loader初始化
                LoaderManager loaderManager = getLoaderManager();
                Bundle bundle = new Bundle();
                bundle.putString("action", "asyHello");

                loaderManager.initLoader(998, bundle, this);

        }

        return ret;
    }


    /**
     * Instantiate and return a new Loader for the given ID.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    @Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        CursorLoader ret = null;
        switch (id) {
            case 998:
                ret = new CursorLoader(getContext(), DataContract.History.CONTENT_URI, null, null, null, null);
                break;
        }
        return ret;

    }

    /**
     * @param loader The Loader that has finished.
     * @param data   The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(Loader<Cursor> loader, Cursor data) {
        //使用changeCursor 因为旧的cursor内部在这个方法中关闭了
        //adapter.swapCursor(data)没有关闭
        adapter.changeCursor(data);
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(Loader<Cursor> loader) {

        adapter.changeCursor(null);
    }

    public void refreshHistory(){
        LoaderManager loaderManager = getLoaderManager();
        loaderManager.restartLoader(998,null,this);
    }


    /**
     *
     * @param parent   The AdapterView where the click happened.
     * @param view     The view within the AdapterView that was clicked (this
     *                 will be a view provided by the adapter)
     * @param position The position of the view in the adapter.
     * @param id       The row id of the item that was clicked.
     */
    private int flag;
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        TextView textView = (TextView) view.findViewById(android.R.id.text1);
        Intent intent  = new Intent(getActivity(), ResetActivity.class);
        String value = textView.getText().toString();
        flag = position;
        intent.putExtra("A", value);
        startActivityForResult(intent, 1);


    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        //Toast.makeText(getContext(), "获取成功", Toast.LENGTH_SHORT).show();
        if(requestCode==1&&resultCode == getActivity().RESULT_OK){
            String txt = data.getStringExtra("B");
            ContentResolver resolver= getActivity().getContentResolver();
            ContentValues values = new ContentValues();
            values.put(DataContract.History.URL, txt);
            int num = resolver.update( DataContract.History.CONTENT_URI,values,"_id = "+flag,null);
            if (num>0) {
                Toast.makeText(getContext(), "更新成功", Toast.LENGTH_SHORT).show();
                refreshHistory();
            }
        }
    }
}
